const employersBlacklistDefault = [
    // Recruitment agencies
    "ALDWYCH CONSULTING LTD",
    "Corriculo Recruitment",
    "Corriculo Ltd",
    "Bennett and Game Recruitment LTD",
    "Ernest Gordon Recruitment",
    "Inspired Recruitment",
    "KO2 Embedded Recruitment Solutions LTD",
    "LM RECRUITMENT SOLUTIONS LTD",
    "Langham Recruitment Limited",
    "MP Recruitment",
    "Rise Technical Recruitment Limited",
    "Verso Recruitment",
    "Verto People",
    "CURE TALENT LIMITED",
    "Belcan Technical Recruiting (UK) Ltd",
    "Cyber Talent Limited",
    "Morson Talent",
    "Pioneer Selection",
    "Bluegate Consulting Ltd",
    "Carbon60 - Eng&Tech",
    "Technical Futures.",
    "Partnerscale Limited",
    "Experis UK",
    "Hays",
    "IC Resources",
    "In Technology Group Limited",
    "Round Peg Solutions",
    "Matchtech Mobility",
    "Yoh Solutions Ltd",
    "ZENOVO LTD",
    "Novus Resourcing Ltd",
    "Omega Resource Group",
    "Redline Group Ltd",
    "Advance TRS",
    "Morgan Ryder",
    "RGS Global",
    "Vantage Consulting",
    "Sigma",
    "Guidant Global",
    "Spectrum It Recruitment Limited",
    "Vantage Consulting Ltd",
    "Hunter Selection",
    "Chroma Recruitment Ltd",
    "Avd Appoint Ltd",
    "Henderson Scott",
    "Interface",
    "La Fosse Associates Ltd",
    "JAM Recruitment Ltd",
    "Yolk Recruitment",
    "Gerrell & Hard",
    "WHD Consulting Ltd",
    "Kingdom People",
    "Glen Callum Associates Ltd",
    "Terry Parris Associates",
    "Client Server",
];
